# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Install Dependencies, Lint

on: [pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [19]
        os: [windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci --legacy-peer-deps
    - name: Cache Prettier
      uses: actions/cache@v3
      env:
        cache-name: cache-prettier
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: node_modules/.cache/prettier
        key: ${{ runner.os }}-prettier-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-prettier-${{ env.cache-name }}-
          ${{ runner.os }}-prettier-
          ${{ runner.os }}-
    - name: Lint
      run: npm run lint
    - name: Spell Check
      run: npm run spellcheck
    # Lint and spell check changes should be pushed
    # to the branch before the branch is merge eligible.
    - name: Check Diff
      run: git diff --exit-code
      shell: bash
